version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: optimeal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: optimeal
    ports:
      - "5434:5432"
    volumes:
      - optimeal_data:/var/lib/postgresql/data

volumes:
  optimeal_data:
